name: Docker Image CI on Git
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
    inputs:
      username:
        description: "give me your username"
        default: "manupadillaph"
        type: "string"
jobs:
  build:
    #runs-on: self-hosted
    runs-on: ubuntu-latest
    steps:
    # - name: task inside job1
    #   run: |
    #     echo The username is ${{ inputs.username }}
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./.appcontainer/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/rats-staking-git:${{ github.sha }}
        cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/rats-staking-git:buildcache
        cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/rats-staking-git:buildcache,mode=max
